# Generated by Django 5.1.2 on 2024-12-26 11:31

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountverified_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Editor", "Editor"),
                    ("Authore", "Authore"),
                    ("User", "User"),
                ],
                default="User",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
