# Generated by Django 5.1.2 on 2024-12-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_status_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
