# Generated by Django 5.1.2 on 2024-12-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
