# Generated by Django 5.1.2 on 2024-12-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address2",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
