# Generated by Django 5.1.2 on 2024-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_customuser_address_customuser_address1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password1",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password2",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
