# Generated by Django 5.1.2 on 2025-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_password1_customuser_password2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
