# Generated by Django 5.1.4 on 2025-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_customuser_last_login_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password1",
            field=models.CharField(default="", max_length=100),
        ),
    ]
