# Generated by Django 5.1.4 on 2025-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_passwordforgotresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password1",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
