# Generated by Django 5.1.4 on 2025-02-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_customuser_password1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password2",
        ),
    ]
