# Generated by Django 5.1.2 on 2025-01-08 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="view_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
