# Generated by Django 5.1.2 on 2025-01-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_postyoutubevideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvideo",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="blog.post",
            ),
        ),
    ]
