# Generated by Django 5.1.2 on 2025-01-10 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_postvideo_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saved",
            field=models.ManyToManyField(
                blank=True, related_name="saved_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
