# Generated by Django 5.1.2 on 2025-01-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_postvideo_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="postvideo",
            name="size",
            field=models.CharField(default="", max_length=100),
        ),
    ]
