# Generated by Django 5.1.2 on 2025-01-27 13:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_postvideo_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="postvideo",
            name="created_time",
            field=models.DateField(default=blog.models.PostVideo.get_current_month),
        ),
    ]
