# Generated by Django 5.1.4 on 2025-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_postvideo_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("published", "published"), ("draft", "draft")],
                default="published",
                max_length=30,
            ),
        ),
    ]
