# Generated by Django 5.1.2 on 2025-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvideo",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
