# Generated by Django 5.1.4 on 2025-02-06 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supportChat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGroupToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
